version: '3'
services:
  web:
    build:
      # context, to tell which directory reltauvely.
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
# We will create another service to run tests
  tests:
    build:
      # context, to tell which directory reltauvely.
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
